[package]
name = "ico"
version = "0.1.0"
description = "Created with Goriant"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "ico"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.6.0"
anchor-spl = "0.6.0"
