[package]
name = "main-staking"
version = "1.0.0"
description = "Created by Goriant Team"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "main_staking"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = "0.5.0"
anchor-spl = "0.5.0"
